import { createElement } from '@lwc/engine-dom';
import Concept_dynamicEventStrategySwitching from 'c/concept_dynamicEventStrategySwitching';

describe('c-concept-dynamic-event-strategy-switching', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-concept-dynamic-event-strategy-switching', {
            is: Concept_dynamicEventStrategySwitching
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});